### ISSUE TITLE
  Edit New issue Giving default height and width in for croping box 

### ISSUE THREAD

**Issue by sidaurukfreddy** [codepo8/simplethumbnails#2]
hello been strugling in this issue, already make post in his blog but still no respond so i read all comment in his blog then i found you,

Quick question here is <a href="http://codepen.io/sidaurukfreddy/pen/BoeWzr">Demo</a>

My question is how can i make box for croping has default height, let say
height : 500px;
width: 500px

Reminder juts for croping box, got source from <a href="http://tympanus.net/codrops/2014/10/30/resizing-cropping-images-canvas/comment-page-1/#comments">Here</a>

Thanks

**Comment by codepo8** [comment]
I don't understand how this is an issue of my code. Do you want to add a box to crop parts of the thumbnail or create them from a cropped part? That is a massive re-write.

**Comment by sidaurukfreddy** [comment]
Sorry i just found this link in that blog so i posted in here
